/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import extras.Imagen;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.UIManager;

/**
 *
 * @author BRAYAN
 */
public class Desktop extends javax.swing.JFrame {

    /**
     * Creates new form Desktop
     */
    
    private Dimension dim_screen;
    private Rectangle screen;
    private Imagen img;
    
    public Desktop() {
        try {
            initComponents();
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
        }
        
        
        //ESTABLECER EL JFRAME COMO TAMAÑO ENTERO DE LA PANTALLA
        this.setTitle("Windows Desktop");
        this.setSize(1000,600);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        dim_screen = Toolkit.getDefaultToolkit().getScreenSize();
        screen = new Rectangle(dim_screen);
        this.setBounds(screen);
        
        //SE CARGA LA IMAGEN
        img = new Imagen(dim_screen.width, dim_screen.height - inicio_pnl.getHeight());
        desktop_pnl.add(img);
        desktop_pnl.repaint();
        
        //CREA EL MENU DE NUEVA CARPETA
        newFolder.setText("Nueva carpeta");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        context = new javax.swing.JPopupMenu();
        newFolder = new javax.swing.JMenuItem();
        inicio_pnl = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        desktop_pnl = new javax.swing.JPanel();

        newFolder.setText("jMenuItem1");
        context.add(newFolder);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        inicio_pnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inicio_pnl.setPreferredSize(new java.awt.Dimension(610, 50));

        lblHora.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("Hora:");

        javax.swing.GroupLayout inicio_pnlLayout = new javax.swing.GroupLayout(inicio_pnl);
        inicio_pnl.setLayout(inicio_pnlLayout);
        inicio_pnlLayout.setHorizontalGroup(
            inicio_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicio_pnlLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 489, Short.MAX_VALUE)
                .addComponent(lblHora)
                .addGap(31, 31, 31))
        );
        inicio_pnlLayout.setVerticalGroup(
            inicio_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
            .addGroup(inicio_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(inicio_pnl, java.awt.BorderLayout.SOUTH);

        desktop_pnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        desktop_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desktop_pnlMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                desktop_pnlMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout desktop_pnlLayout = new javax.swing.GroupLayout(desktop_pnl);
        desktop_pnl.setLayout(desktop_pnlLayout);
        desktop_pnlLayout.setHorizontalGroup(
            desktop_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktop_pnlLayout.setVerticalGroup(
            desktop_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        getContentPane().add(desktop_pnl, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseReleased

    private void desktop_pnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktop_pnlMousePressed
        // TODO add your handling code here:
            if(evt.isPopupTrigger()){
            context.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_desktop_pnlMousePressed

    private void desktop_pnlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktop_pnlMouseReleased
        // TODO add your handling code here:
            if(evt.isPopupTrigger()){
            context.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_desktop_pnlMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu context;
    private javax.swing.JPanel desktop_pnl;
    private javax.swing.JPanel inicio_pnl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblHora;
    private javax.swing.JMenuItem newFolder;
    // End of variables declaration//GEN-END:variables
}
